apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-default-yaml-cli
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev2-cli
  source:
    repoURL: https://github.com/Chanheeeee/jch-argocd.git
    targetRevision: main
    path: nginx-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
