apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev2-cli
  namespace: argo # argocd 배포되어있는 네임스페이스
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: dev Project
  sourceRepos:
  - '*' # 전체 repo 허용
  destinations: #Only permit applications to deploy to the 'default' namespace in the same cluster
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
